server:
  port: 8080

spring:
  datasource:
    username: root
    password: PIom0163
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
  threads:
    virtual:
      enabled: true