server:
  port: 8080

spring:
  datasource:
    username: root
    password: PIom0163
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: PIom0163

logging:
  level:
    io.github.sxh705.user: debug

